# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67d20842d01bbb13fcaa27aa677e31a0df76a98dbc1f69c5badb52d95e210ea76dbe3513215ad2c8223cfdb2b7e1cb3e58b78d1ee5cb67d5296559c55ae5aa31

test:
  secret_key_base: dc53ee0400fa2a136bd92ae132d55d3f8677b7cad0ae77f436c03987613f9a9e52794134852044d6029071e7177103a2276111e4297690f28276d802510debd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
